### ISSUE TITLE
Hex UI tweak

### ISSUE THREAD

**Issue by mayarichman** [tristen/hcl-picker#2]
It would be sweet if the hex values were in text boxes to make them easier to copy and paste. It's a would-be-nice, not a gotta-have-it.

**Comment by ajashton** [comment]
They shouldn't all be in separate text boxes - that would make copying & pasting them all a pain. Currently if you click on one, all are selected. Maybe clicking on a code just selects that one, and make select-all a double-click or a separate button?

**Comment by mayarichman** [comment]
Yeah, that makes sense to me. Thanks for the quick reply!
